#!/bin/bash

# TODO: the embed link had to be manually adjusted
# TODO: would be nice to not have to juggle the two localhost urls

# Export the page /articles/first-steps with wget to the site/ directory

pages=(
    "http://localhost:8123/articles/first-steps"
    "http://127.0.0.1:5000/embed"
)

output_dir="docs"

rm -rf $output_dir

for page in "${pages[@]}"; do
  wget --no-clobber \
       --page-requisites \
       --html-extension \
       --convert-links \
       --domains localhost \
       --no-host-directories \
       --directory-prefix="$output_dir" \
       "$page"
done